### ISSUE TITLE
PAL NES Linearity Test large ellipse is slightly too wide

### ISSUE THREAD

**Issue by Zinfidel** [pinobatch/240p-test-mini#33]
### Summary
The PAL NES Linear Test large main ellipse is 2 pixels too wide, such that after aspect ratio correction (using the test's own 11:8 PAR assumption), the resulting ellipse is very slightly wider than it is tall.

### Disclaimer
I am not sure if this is an actual problem or if there are other factors of NES display that I'm just not familiar with contributing to this disparity. I am by no means an expert on NES display technology and have discovered this problem purely in the realm of emulation, video editing, and online sources. There's plenty I do not understand about how an NES does video, and I fully realize that once this test is used on an actual CRT television, differences like this one that I've spotted are probably totally negligible or might actually be correct when not being shown on a modern square-pixel monitor.

### Details
First let me say that all of my calculations and measurements are done in the realm of pixels rather than dots on a TV, so are quite artificial. The PAL NES large ellipse has a width of 176 pixels and a height of 239 pixels. Applying PAR correction yields clean integer dimensions of 242x239. When blown up, and measured in a paint program with a circle tool, the ellipse is slightly flatter than circle. If we instead use the PAR values from [nesdev's overscan page](https://wiki.nesdev.com/w/index.php/Overscan) (1.3862), the problem worsens as this value is even wider.

### Possible Solution
Contracting the main ellipse by 2 pixels makes a nearly-perfect circle after PAR correction. 174 * PAR = 239.25, which is very close to the height.

### Example Images
Current PAL Linearty test after scaling the image a bit and correcting for a PAR of 11:8, with paint.NET's circle selection tool visible
![image](https://user-images.githubusercontent.com/1929934/117860556-48468200-b245-11eb-8d23-90e30f6d96a1.png)

My sloppy attempt at redrawing the ellipse in paint.NET:
![image](https://user-images.githubusercontent.com/1929934/117860145-d0785780-b244-11eb-849b-6cb39f19e03d.png)

After blowing up my adjusted version of the linearity test and correcting for PAR, this is the result (with circle tool visible):
![image](https://user-images.githubusercontent.com/1929934/117860806-93f92b80-b245-11eb-8dec-dadb73093264.png)

**Comment by pinobatch** [comment]
Upstream has been moving toward replacing Linearity with Monoscope. I followed suit in the NES version, which now uses the less-inaccurate 18:13 assumption for PAL PAR.
