### ISSUE TITLE
Famicom support

### ISSUE THREAD

**Issue by 8lall0** [pinobatch/240p-test-mini#36]
Hi,
i want to ask if the suite supports also the Japanese NTSC Famicom :)

Thank you!

**Comment by pinobatch** [comment]
240p Test Suite for NES should work fine on an NTSC Family Computer or a PAL famiclone. When it recognizes the timing signature of the most common PAL famiclone, it writes "Dendy" on the main menu. A translation of help text into Japanese is not yet planned.

**Comment by pinobatch** [comment]
Appears answered.
