### ISSUE TITLE
Mode text rendered incorrectly in the GBC port

### ISSUE THREAD

**Issue by JoseJX** [pinobatch/240p-test-mini#40]
Using the GBC port, in the shadow sprite demo, the text that describes the mode is rendered incorrectly. Looking at the tile RAM, it looks like the Donna image overwrote the text for these sections.

To reproduce:

1. Build the current git version for GBC
2. Boot the program and select the "Shadow sprite" demo
3. Press A + Up and observe that the text isn't rendered properly on the lower right
4. Press A + Right to switch to the next background
5. Press A + Up and observe that the text is rendered properly, this is the expected behavior

**Comment by pinobatch** [comment]
Looks like I fixed this in 3cd23de1
